import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument } from 'mongoose';

export type TenantInvoiceDocumentModel = HydratedDocument<TenantInvoice> & {
  createdAt: Date;
  updatedAt: Date;
};

/**
 * Stories 15–22, 27 — tenant invoices generated by the CAM engine.
 *
 * Two flavors:
 *   - original   — produced from a single bill, 1:1 (Story 15). billId is set,
 *                  line_items is null.
 *   - adjustment — produced by a reconciliation run; one per affected unit
 *                  per run. billId is null (it spans multiple bills),
 *                  line_items[] enumerates per-bill deltas.
 *
 * Story 18 — no Delete. Both kinds are append-only; an "edit" is captured
 * via payment_history (Story 21) or as a new adjustment.
 */
export type TenantInvoiceKind = 'original' | 'adjustment';

/**
 * Algorithm case the engine took. Matches the four-branch state in the
 * UX's generateInvoicesForBatch:
 *   excluded  — bill's category is in the unit's exclusions; threshold
 *                still updated, billable = 0.
 *   pre_base  — threshold_after <= base_amount; under base, billable = 0.
 *   crossover — threshold_before < base AND threshold_after > base; only
 *                the over-base portion × share is billable.
 *   post_base — threshold_before >= base_amount; full bill × share billable.
 */
export type TenantInvoiceCaseType =
  | 'excluded'
  | 'pre_base'
  | 'crossover'
  | 'post_base';

export type TenantInvoiceStatus =
  | 'draft'
  | 'pending_review'
  | 'committed'
  | 'void';

export type VarianceTag = 'compliant' | 'over_billed' | 'under_billed';

/** Story 21 — payment history audit trail. */
@Schema({ _id: false })
export class PaymentEntry {
  @Prop({ type: Number, required: true })
  amount: number;

  @Prop({ type: Date, required: true })
  paid_at: Date;

  @Prop({ type: String, default: null })
  method: string | null;

  @Prop({ type: String, default: null })
  reference: string | null;

  @Prop({ type: String, default: null })
  notes: string | null;

  @Prop({ type: String, required: true })
  recorded_by: string;

  @Prop({ type: Date, required: true })
  recorded_at: Date;
}
const PaymentEntrySchema = SchemaFactory.createForClass(PaymentEntry);

/** Story 27 — per-user reminders on an invoice. */
@Schema({ _id: false })
export class InvoiceReminder {
  @Prop({ type: String, required: true })
  reminder_id: string;

  @Prop({ type: String, required: true })
  user_id: string;

  @Prop({ type: Date, required: true })
  remind_at: Date;

  @Prop({ type: String, default: '' })
  note: string;

  /** in_app / email / both. */
  @Prop({ type: String, default: 'in_app' })
  channel: string;

  /** Set by the cron job (Story 28) once fired so we don't re-fire. */
  @Prop({ type: Date, default: null })
  fired_at: Date | null;
}
const InvoiceReminderSchema = SchemaFactory.createForClass(InvoiceReminder);

/** Line item inside an adjustment invoice — one row per bill being adjusted. */
@Schema({ _id: false })
export class AdjustmentLineItem {
  @Prop({ type: String, required: true })
  billId: string;

  @Prop({ type: String, default: null })
  bill_vendor_name: string | null;

  @Prop({ type: Date, default: null })
  bill_invoice_date: Date | null;

  @Prop({ type: Number, default: null })
  bill_total_amount: number | null;

  /** The original invoice this delta is correcting (if any). */
  @Prop({ type: String, default: null })
  original_invoice_id: string | null;

  /** What was actually invoiced for this bill before the adjustment. */
  @Prop({ type: Number, required: true })
  original_invoiced_amount: number;

  /** What the canonical replay said it should have been. */
  @Prop({ type: Number, required: true })
  canonical_invoiced_amount: number;

  /** canonical − original. Positive = tenant owes more, negative = credit. */
  @Prop({ type: Number, required: true })
  delta: number;

  @Prop({ type: String, default: '' })
  reason: string;
}
const AdjustmentLineItemSchema =
  SchemaFactory.createForClass(AdjustmentLineItem);

@Schema({ collection: 'tenant_invoices', timestamps: true })
export class TenantInvoice {
  /** Public id, e.g. inv_<hex> */
  @Prop({ required: true, index: { unique: true, sparse: true } })
  invoiceId: string;

  @Prop({
    required: true,
    enum: ['original', 'adjustment'],
    default: 'original',
    index: true,
  })
  invoice_kind: TenantInvoiceKind;

  /** Set only for `original` invoices. Null for `adjustment`. */
  @Prop({ type: String, default: null, index: true })
  billId: string | null;

  @Prop({ required: true, index: true })
  unit_id: string;

  @Prop({ required: true, index: true })
  property_id: string;

  @Prop({ required: true, index: true })
  portfolio_id: string;

  /** Display sugar denormalized from Unit so the ledger UI doesn't JOIN. */
  @Prop({ type: String, default: null })
  unit_code: string | null;

  @Prop({ type: String, default: null })
  tenant_name: string | null;

  // ── Engine inputs at time of generation (snapshotted for audit) ──────
  @Prop({ type: Number, default: null })
  bill_amount: number | null;

  @Prop({ type: Number, default: null })
  share_pct: number | null;

  @Prop({ type: Number, default: null })
  base_amount_at_time: number | null;

  @Prop({ type: Number, default: null })
  base_year_at_time: number | null;

  @Prop({ type: Number, default: null })
  admin_fee_pct_at_time: number | null;

  // ── Engine outputs ─────────────────────────────────────────────────
  @Prop({ type: Number, default: null })
  threshold_before: number | null;

  @Prop({ type: Number, default: null })
  threshold_after: number | null;

  @Prop({ type: Number, default: 0 })
  under_base_portion: number;

  @Prop({ type: Number, default: 0 })
  over_base_portion: number;

  @Prop({ type: Number, default: 0 })
  admin_fee: number;

  /** Net amount owed by the tenant on this invoice (may be 0). */
  @Prop({ type: Number, required: true, default: 0 })
  invoice_amount: number;

  @Prop({
    type: String,
    enum: ['excluded', 'pre_base', 'crossover', 'post_base'],
    default: null,
  })
  case_type: TenantInvoiceCaseType | null;

  /** Calendar year the threshold accumulation belongs to. */
  @Prop({ type: Number, required: true, index: true })
  calendar_year: number;

  // ── Category & rules ──────────────────────────────────────────────
  @Prop({ type: String, default: null, index: true })
  expense_category: string | null;

  @Prop({ type: [String], default: [] })
  applied_cam_rule_ids: string[];

  // ── Lifecycle ─────────────────────────────────────────────────────
  @Prop({
    required: true,
    enum: ['draft', 'pending_review', 'committed', 'void'],
    default: 'draft',
    index: true,
  })
  status: TenantInvoiceStatus;

  @Prop({ type: Date, default: null })
  committed_at: Date | null;

  @Prop({ type: String, default: null })
  committed_by: string | null;

  // ── Payments + variance (Stories 21, 22) ──────────────────────────
  @Prop({ type: Number, default: null })
  tenant_paid_amount: number | null;

  @Prop({
    type: String,
    enum: ['compliant', 'over_billed', 'under_billed'],
    default: null,
    index: true,
  })
  variance_tag: VarianceTag | null;

  @Prop({ type: [PaymentEntrySchema], default: [] })
  payment_history: PaymentEntry[];

  // ── Reminders (Stories 27, 28) ────────────────────────────────────
  @Prop({ type: [InvoiceReminderSchema], default: [] })
  reminders: InvoiceReminder[];

  // ── Adjustment-invoice extras ─────────────────────────────────────
  /** Set for `adjustment` invoices. */
  @Prop({ type: String, default: null, index: true })
  reconciliation_runId: string | null;

  /** Populated only for `adjustment` invoices. */
  @Prop({ type: [AdjustmentLineItemSchema], default: undefined })
  line_items?: AdjustmentLineItem[];
}

export const TenantInvoiceSchema = SchemaFactory.createForClass(TenantInvoice);

TenantInvoiceSchema.index({ property_id: 1, calendar_year: 1, status: 1 });
TenantInvoiceSchema.index({ unit_id: 1, calendar_year: 1, createdAt: 1 });
TenantInvoiceSchema.index({ portfolio_id: 1, status: 1, createdAt: -1 });
TenantInvoiceSchema.index({ billId: 1, unit_id: 1 }, { sparse: true });
