import { CreateBillDto, TransitionBillDto, UpdateBillDto } from '../dto/bill.dto';
import { BillsService } from '../services/bills.service';
export declare class BillsController {
    private readonly svc;
    constructor(svc: BillsService);
    create(dto: CreateBillDto): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }>;
    list(portfolioId: string | undefined, propertyId: string | undefined, status: string | undefined, sessionId: string | undefined, from: string | undefined, to: string | undefined): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }[]>;
    newSession(): {
        session_id: string;
    };
    getOne(billId: string, portfolioId: string | undefined): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }>;
    update(billId: string, portfolioId: string | undefined, dto: UpdateBillDto): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }>;
    transition(billId: string, portfolioId: string | undefined, dto: TransitionBillDto): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }>;
}
