import { Model } from 'mongoose';
import { CreateBillDto, TransitionBillDto, UpdateBillDto } from '../dto/bill.dto';
import { BillDocumentModel, BillStatus } from '../schemas/bill.schema';
export declare class BillsService {
    private readonly model;
    constructor(model: Model<BillDocumentModel>);
    create(dto: CreateBillDto, actor?: string): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }>;
    list(filter: {
        portfolio_id: string;
        property_id?: string;
        status?: BillStatus | BillStatus[];
        session_id?: string;
        invoice_date_from?: string;
        invoice_date_to?: string;
    }): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }[]>;
    getOne(portfolioId: string, billId: string): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }>;
    update(portfolioId: string, billId: string, dto: UpdateBillDto): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }>;
    transition(portfolioId: string, billId: string, dto: TransitionBillDto): Promise<{
        billId: any;
        portfolio_id: any;
        property_id: any;
        unit_id: any;
        vendor_invoice_number: any;
        vendor_name: any;
        vendor_id: any;
        invoice_date: any;
        due_date: any;
        service_period_start: any;
        service_period_end: any;
        total_amount: any;
        currency: any;
        expense_category: any;
        status: any;
        source_file_url: any;
        source_page_range: any;
        ocr_confidence: any;
        missing_fields: any;
        additional_meta_data: any;
        session_id: any;
        created_by: any;
        accepted_by: any;
        accepted_at: any;
        createdAt: any;
        updatedAt: any;
    }>;
    markCommitted(portfolioId: string, billIds: readonly string[]): Promise<number>;
    newSession(): string;
    private computeMissingFields;
}
